spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false
    username: root
    password: 12345678
    # 连接池类型
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations:
    - classpath:mappers/*.xml